### ISSUE TITLE
hd-idle for Bullseye

### ISSUE THREAD

**Issue by auanasgheps** [adelolmo/adelolmo.github.io#2]
Hello!
OpenMediaVault 6 is now based on Bullseye and will be released as stable soon.
Could you please upload hd-idle for bullseye as well?
Thanks!

**Comment by adelolmo** [comment]
Hi @auanasgheps 

I've added hd-idle to bullseye.

| Distribution | Component | Architecture | Package | Version |
| ------------ | ------ | -------- | ------- | ------- |
|bullseye|main|i386|hd-idle|1.16|
|bullseye|main|amd64|hd-idle|1.16|
|bullseye|main|armhf|hd-idle|1.16|
|bullseye|main|arm64|hd-idle|1.16|

**Comment by auanasgheps** [comment]
Thank you!
