### ISSUE TITLE
hd-idle: i386 not supported in repo bullseye

### ISSUE THREAD

**Issue by ph1248** [adelolmo/adelolmo.github.io#3]
Hi, 

I am running debian bullseye in a minimal configuration on a HP Thinclient, i386 architecture. I wnat to install hd-idle via your repository. I am a linux beginner, on my way to intermediate. 

I think I successfully added your repository "http://adelolmo.github.io/bullseye bullseye InRelease".

Then, when I do "sudo apt-get update", the result is: 

```
OK:2 http://deb.debian.org/debian bullseye InRelease
OK:3 http://deb.debian.org/debian bullseye-updates InRelease
OK:4 http://security.debian.org/debian-security bullseye-security InRelease
OK:1 https://adelolmo.github.io/bullseye bullseye InRelease
Paketlisten werden gelesen… Fertig
N: Das Laden der konfigurierten Datei »main/binary-i386/Packages« wird übersprungen, da das Depot »http://adelolmo.github.io/bullseye bullseye InRelease« die Architektur »i386« nicht unterstützt.
```

Sorry for the german version, it means mor or less:  "loading file »main/binary-i386/Packages« will be skipped, since repository  »http://adelolmo.github.io/bullseye bullseye InRelease« does not support architecture »i386« .

When I try to install hd-idle, it installs the old version 1.05+ds-2 from the debian repo.

Am I doing it wrong?

Thanks for your help!  

Best regards
Philipp

**Comment by adelolmo** [comment]
Hi @ph1248 

I just added hd-idle to bullseye. 
So far I've never bothered adding i386 packages to this repo, but this time I did it for the occasion :)

**Comment by ph1248** [comment]
Wow, that was quick! Thanks a lot for your effort - download and install worked like a charm.
