### ISSUE TITLE
Debian 12: legacy keyring

### ISSUE THREAD

**Issue by juantxorena** [adelolmo/adelolmo.github.io#4]
Hello,

I'm using your repo for hd-idle in debian (thanks, btw). In bookworm, when doing an apt-get update, it gives a warning about a legacy keyring file:

`W: http://adelolmo.github.io/bookworm/dists/bookworm/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.`

Just pointing it out, just in case it needs to be fixed in the future. I can have a look if you want.

**Comment by adelolmo** [comment]
Hi @juantxorena 
Thank you for reporting the issue.
Could you please try this steps to add the repo?
```
sudo apt-get install apt-transport-https
wget -O- https://adelolmo.github.io/andoni.delolmo@gmail.com.gpg.key | sudo tee /usr/share/keyrings/adelolmo-archive-keyring.gpg
echo "deb http://adelolmo.github.io/$(lsb_release -cs) $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/adelolmo.github.io.list
```
Then run `apt-get update` and let me know if the warning message is gone.

**Comment by adelolmo** [comment]
I successfully tested this approach:
```
sudo curl -sS -fsSLo /usr/share/keyrings/adelolmo-archive-keyring.gpg https://adelolmo.github.io/andoni.delolmo@gmail.com.gpg
echo "deb [signed-by=/usr/share/keyrings/adelolmo-archive-keyring.gpg] https://adelolmo.github.io/$(lsb_release -cs) $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/adelolmo.github.io.list
```
Please let me know if it works for you too.

**Comment by juantxorena** [comment]
Hola,

sorry, I couldn't try it before. I tried those two commands and they work. I guess I can close the bug. Maybe it should be documented somewhere, or is it something that every debian user should know? (I only use it in VMs and containers, I don't have a lot of experience).
