### ISSUE TITLE
i386 version for debian-bookworm repo?

### ISSUE THREAD

**Issue by ph1248** [adelolmo/adelolmo.github.io#5]
Hi @adelolmo , 

in January 2022 I had asked you to add an i386 version of hd-idle to the debian bullseye repo, and you had been so kind to do it immediately (see #3). Thanks again for that. 

Now I would like to upgrade to bookworm. May I ask you again to include an i386 version in that repo? Debian is still a great way to extend the working life of older hardware, and hd-idle is incredibly useful in such projects. Many thanks in advance!

Philipp

**Comment by adelolmo** [comment]
done
