### ISSUE TITLE
hd-idle for Ubuntu Noble 24.04 (LTS)

### ISSUE THREAD

**Issue by V33m** [adelolmo/adelolmo.github.io#6]
Cheers Andoni!

When you find time, could you please add hd-idle for Ubuntu Noble 24.04 (LTS)?

If you would like to future proof, you might add Debian 13 (trixie) which likely will release mid 25 at the same time.

**Comment by adelolmo** [comment]
Hi @V33m 

Done :)

Thank you for the heads up!

**Comment by V33m** [comment]
Awesome! Thanks :)
